apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-dep
  namespace: next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next-app
          image: xanderflinn/deploy-demo:79ba42b7709916937789b10ddc75ab090f1613e4
          ports:
            - containerPort: 3000
