apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: next-secret
  namespace: next
spec:
  encryptedData:
    .env: AgB6df0LUhu0jRa4n5065oaeNZmbJS2JkZhtXFtEkk1dcZQw4DgnE0L6ei0xPPg5mGiy46bHSfhQAgolKMUKhCrNXCl7O7RZ0a5lIpraAh30qa/UACWmUl+dBdzrA477NxHrTeYvq3z+Z+mt2IprLQsEiBxvRO544ttUCYvamoieYNzEWVKintL4erz6dTZc01Mq1ZwgRoksAyLriGWBRo7rAOvo1Q/uvcU1I5W8mnJhJrVewb7LJctuv2xCMYWxwCE1lA43O2vXFIIma099GhLW+L4R1iDIH8ZAAzQ79KqczW6BZ5pFOMaRJW6hqDc+lUmPsc//k/Y5AlyhXMsOoH1alMIuqCobYepNYGRrPEkBeYYPsRpMo8Knk9W1AXM0hnSSklOIl5Njt9kuAhDJwhhxDNM8y1ADDYIL2qTQW6X7Zb4NHnH+z9+SdErq+zSN2np4yaKytWeoX5kSYKSxdqx3SgtnHwOO6wMTOHlRyqtzq6R0i242kjyKLa0rAQ4W4VKXBsS6zKY8Sb1dRKlDBAyrrhTRvOffVIKbR3EYk/rjzADlI04KnTsXd36aaabkDxfKnNMgVCx0d6VTkAVeiSaF+0iNsedNg9kROvDPwh2LAlWZEL6h2WQox7b58+4PH8n/Rq9EcUOQ3qqrvFhYE62x371G9FnxHaBcXW33EBckLyrd6n4TOLrXdoxpZZfhliDMapF4I23xiGywoOl3vFyEXxaXW/08nargHTOln+6LVNj/3+AEFi+j8XXBiD8KMiiPcZrckA==
  template:
    metadata:
      name: next-secret
      namespace: next
