apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-dealer-dep
  namespace: car-dealer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-dealer-app
  template:
    metadata:
      labels:
        app: car-dealer-app
    spec:
      containers:
        - name: car-dealer-app
          image: xanderflinn/car-dealer-cms:187783ecc8af6071686d2f5aa50cd8617f4b1201
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          volumeMounts:
            - name: env-file
              readOnly: true
              mountPath: "/app/.env"
              subPath: .env
      volumes:
        - name: env-file
          secret:
            secretName: car-dealer-secret
