apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: car-dealer-hpa
  namespace: car-dealer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: car-dealer-dep
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
